export const GET_CATEOGARIES_LIST = "GET_CATEOGARIES_LIST";
export const SET_CATEOGARIES_LIST = "SET_CATEOGARIES_LIST";

export const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST";
export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";

export const GET_PRODUCTS_LIST_ITALIAN = "GET_PRODUCTS_LIST_ITALIAN";
export const SET_PRODUCTS_LIST_ITALIAN = "SET_PRODUCTS_LIST_ITALIAN";

export const GET_PRODUCTS_LIST_IRISH = "GET_PRODUCTS_LIST_IRISH";
export const SET_PRODUCTS_LIST_IRISH = "SET_PRODUCTS_LIST_IRISH";

export const GET_PRODUCTS_LIST_ANIMAL = "GET_PRODUCTS_LIST_ANIMAL";
export const SET_PRODUCTS_LIST_ANIMAL = "SET_PRODUCTS_LIST_ANIMAL";

export const GET_PRODUCTS_LIST_FLOWER = "GET_PRODUCTS_LIST_FLOWER";
export const SET_PRODUCTS_LIST_FLOWER = "SET_PRODUCTS_LIST_FLOWER";

export const GET_PRODUCTS_LIST_CHRISTMAS = "GET_PRODUCTS_LIST_CHRISTMAS";
export const SET_PRODUCTS_LIST_CHRISTMAS = "SET_PRODUCTS_LIST_CHRISTMAS";

export const GET_PRODUCTS_LIST_VALENTINES = "GET_PRODUCTS_LIST_VALENTINES";
export const SET_PRODUCTS_LIST_VALENTINES = "SET_PRODUCTS_LIST_VALENTINES";
