export const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST";
export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";

export const GET_DEFAULT_PRODUCTS_LIST = "GET_DEFAULT_PRODUCTS_LIST";
export const SET_DEFAULT_PRODUCTS_LIST = "SET_DEFAULT_PRODUCTS_LIST";
